### PR TITLE
fix `frankenphp trust` failing because admin api isn't started #1846

### LINKED ISSUE #1846: Installing rpm/deb package fails to install CA trust
### What happened?

It seems caddy has changed this to use the admin API, rather than going through the filesystem. So running `frankenphp trust` fails with an error that localhost:2019 refused connection.

I'm not sure what the best way to work around this is. We could start the server before in theory, but that would lead to installation failure if anything already listens to :80, :443 or :2019.

@mholt ?

### Build Type

Custom (tell us more in the description)

### Worker Mode

No

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
-
```

### Relevant log output

```shell
Error: requesting CA info: performing request: Get "http://localhost:2019/pki/ca/local": dial tcp 127.0.0.1:2019: connect: connection refused
```

### PR DESCRIPTION
**Pull request by henderkes**
closes #1846
update frankenphp trust command to start it before so the admin api call doesn't fail 

I hope this is the right way to go about it, I couldn't find an alternative

### CODE REVIEW

File: package/debian/postinst.sh [hunk 1]
```diff
@@ -63,5 +63,9 @@ if command -v setcap >/dev/null 2>&1; then
 fi
 
 if [ -x /usr/bin/frankenphp ]; then
+	HOME=/var/lib/frankenphp /usr/bin/frankenphp run --config /dev/null &
+	FRANKENPHP_PID=$!
```
Comment (henderkes) [inline package/debian/postinst.sh:67]: alternatively, we could use 
`frankenphp start`
and follow it up with 
`frankenphp stop`

**Comment by henderkes** [comment]
Can we get this merged before the rpm/deb package PR? I have tried this and it works reliably, although it takes like 3-5 seconds.

**Comment by dunglas** [comment]
Thanks!
